### ISSUE TITLE
Drupal modules are required to be licensed at GPL-2.0 or later

### ISSUE THREAD

**Issue by kreynen** [tenon-io/tenon-drupal#1]
https://www.drupal.org/about/licensing#q7

> If I write a module or theme, do I have to license it under the GPL?
> 
> Yes. Drupal modules and themes are a derivative work of Drupal. If you distribute them, you must do so under the terms of the GPL version 2 or later.

**Comment by naterkane** [comment]
@kreynen MIT licenses are GPL compatible. 
"MIT licensed software can be integrated into GPL software, but not the other way around."
see: https://en.wikipedia.org/wiki/MIT_License

**Comment by kreynen** [comment]
True, but the Drupal project has always considered the PHP in modules and themes to be derivative work of Drupal and thus requires them to be licensed at GPL-2.0 and later regardless of where they are distributed from.

You can license any libraries used by a module as MIT and then commit those with the GPL-2.0 licensed PHP (with an approved exception from https://www.drupal.org/project/drupal_lwg) to Drupal.org.  If the combined package is distributed from Drupal.org, the MIT licensed code would be redistributed as GPL-2.0.  If you continue distributing from Github, you'd be able to do that with part of the code under GPL-2.0 and part under MIT.

Considering modules as derivative work has been the Drupal project policy for > 10 years. It has been challenged many times and you certainly are free to do that, but it has been thoroughly vetted multiple legal teams and never changed. IANAL, but AFAIK there is no established legal precedent on this.  While MIT licensed code is GPL compatible, allowing modules to be licensed at MIT would mean admitting they weren't derivative works and don't inherit the GPL-2.0 license. That would open the door to using any license, which is something the Drupal Association would put substantial resources into fighting.

I ended up here from https://www.drupal.org/node/2857808.  My role in Drupal's Licencing Working Group does not give me any authority to roam the internet looking for projects that aren't inline with Drupal's licensing policies, but I can't see any way the Drupal project would use a service that holds a contradictory view on modules as derivatives.

**Comment by karlgroves** [comment]
Fixed
